Repository prgrms-web-devcourse/fedc3-refactoring-book, pull requests merged in 2023-01, with the labels that each got.

#3 01장 - 리팩터링 첫 번째 예시
  01-리팩터링_첫_번째_예시/01-리팩터링_첫_번째_예시.md
  01-리팩터링_첫_번째_예시/mock/invoices.json
  01-리팩터링_첫_번째_예시/mock/plays.json
  01-리팩터링_첫_번째_예시/statement.after.js
  01-리팩터링_첫_번째_예시/statement.before.js
  01-리팩터링_첫_번째_예시/statement.middle.js
  01-리팩터링_첫_번째_예시/statement.middle2.js
  01-리팩터링_첫_번째_예시/신동우_.md
Labels: 1장

#4 02장 - 리팩터링 원칙
  02-리팩터링_원칙/02-리팩터링_원칙.md
Labels: 2장

#8 03_05장-코드에서나는악취_테스트코드구축_카탈로그보는법
  03-05/03-코드에서_나는_악취.md
  03-05/04-테스트_구축하기.md
  03-05/05-리팩터링_카탈로그_보는_법.md
Labels: 3장, 4장, 5장

#7 06장 - 기본적인 리팩터링
  06-기본적인_리팩터링/06-기본적인_리팩터링.md
Labels: 6장

#11 08장 - 기능이동
  08-기능이동/08-기능이동.md
Labels: 8장
